<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>uk.org.gently.vdoninja</AssemblyName>
    <Nullable>enable</Nullable>
    <LangVersion>8.0</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)\uk.org.gently.vdoninja.sdPlugin\</OutputPath>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog" Version="5.4.0" />
    <PackageReference Include="StreamDeck-Tools" Version="6.3.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

	<ItemGroup>
		<!-- <Content Include="brlogo.ico" /> -->
		<!-- <Content Include="Images\buttonDisabled%402x.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content> -->
		<!-- <Content Include="Images\buttonDisabled.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content> -->
		<!-- <Content Include="Images\buttonEnabled%402x.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content> -->
		<!-- <Content Include="Images\buttonEnabled.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content> -->
		<Content Include="Images\categoryIcon%402x.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Images\categoryIcon.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Images\icon%402x.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Images\icon.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Images\pluginIcon%402x.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Images\pluginIcon.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Images\vdoninja%402x.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Images\vdoninja.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<!-- <Content Include="Images\vm%402x.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Images\vm.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Images\vmTop%402x.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Images\vmTop.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="PropertyInspector\AdvancedKeypress.js">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="PropertyInspector\jquery-3.3.1.min.js">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="PropertyInspector\jquery.highlight-within-textarea.css">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="PropertyInspector\jquery.highlight-within-textarea.js">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="PropertyInspector\VoiceMeeter\AdvancedPTT.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="PropertyInspector\VoiceMeeter\AdvancedKeypress.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="PropertyInspector\VoiceMeeter\AdjustSettingDial.html">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="PropertyInspector\VoiceMeeter\MacroToggle.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="PropertyInspector\VoiceMeeter\AdvancedToggle.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="PropertyInspector\VoiceMeeter\Microphone.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="PropertyInspector\VoiceMeeter\GainAdjustDial.html">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="PropertyInspector\VoiceMeeter\Modify.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content> -->
	</ItemGroup>

</Project>
